- name: install postfix MTA
  apt:
    pkg:
    - postfix
    state: present

- name: updating postfix inet_interfaces
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^inet_interfaces ='
    line: inet_interfaces = 172.17.0.1

- name: updating postfix mynetwork
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: '^mynetworks ='
    line: mynetworks = 192.168.0.0/16, 172.16.0.0/12
